README.md
Rather than deleting the database after 30 days of first write which leads to unpredictable behavior (I wrote this key on day 29, and then it was gone the next day!), delete each key individually after 30 days of inactivity (write operation). Closes #45
=> Automatically clear keys after 30 days since last write

README.md
We'd like more fine-grained control of the output gates
=> Explain "shared-storage-select-url" and "private-aggregation" permissions policy

.github/workflows/build.yml, .github/workflows/preview.yml
We fix the destination of the spec's html file to fix the same problem as mentioned in https://github.com/WICG/fenced-frame/issues/53.
We also separate the building of the spec for PRs into a new workflow action with a different destination, so that they won't interfere with deployment on push.
=> Create separate workflow for PR previews

README.md
We add the option to `keepAlive` a worklet after a `selectURL`/`run` operation. This option will default to false, and if not specified as true, the worklet will close after the operation completes.
=> Add `keepAlive` option to explainer

README.md
We relax the requirement that the URLs used as inputs to `sharedStorage.selectURL()` be k-anonymous.
We currently have event-level reporting, which allows callers to associate a first-party identifier with up to three bits of cross-site data, in spite of any k-anonymity constraints. Meanwhile, requiring the input URLs to be k-anonymous increases the latency and complexity of `selectURL()` calls. Thus, we believe a k-anonymity requirement is of limited benefit and not worth the associated financial, performance, and utility costs.
Without k-anonymity, first-party information can be encoded in an input URL and thereby joined with cross-site data through the URL-selection process. We therefore add additional entropy limits to govern `selectURL()`'s use and mitigate its privacy impact.
In …
=> Replace k-anonymity requirement for `selectURL()` input URLs with per per-page-load entropy bit budgets

README.md
We propose adding support to write to and delete from Shared Storage via a new HTTP response header `Shared-Storage-Write`, which will be able to  trigger `set()`, `append()`, `delete()`, and `clear()` operations. This will make our API surface more flexible and thereby provide greater utility to developers. Writing from headers should provide a large performance improvement over creating a cross-origin iframe and writing from there, if a network request is otherwise required.
To use the `Shared-Storage-Write` response header, the corresponding HTTP request header `Shared-Storage-Writable: ?1` must first be sent.
We plan to support making requests with the request header `Shared-Storage-Writable: ?1` by way of `fetch(<url>, {sharedStorageWritable: true})`, as well as a new content/IDL …
=> Add support for writing from response headers

README.md
At least initially, we will only support sending keys and/values via response headers as either [printable-ASCII-character](https://www.rfc-editor.org/rfc/rfc20.html) [Strings](https://www.rfc-editor.org/rfc/rfc8941.html#name-strings), or as [Byte Sequences](https://www.rfc-editor.org/rfc/rfc8941.html#name-byte-sequences) with [UTF-8](https://www.rfc-editor.org/rfc/rfc3629.html) as the intended character set.
The decision to restrict our support of [Byte Sequences](https://www.rfc-editor.org/rfc/rfc8941.html#name-byte-sequences) to a single character encoding will allow us to avoid the additional complexity of either using heuristics to try to determine the intended character encoding, or else requiring that the encoding be specified with the [Byte …
=> Only support UTF-8 in response header Byte Sequences

README.md
According to [RFC8941](https://www.rfc-editor.org/rfc/rfc8941.html#name-parameters), "parameter keys cannot contain uppercase letters". So we fix the parameter key in response headers corresponding to `ignoreIfPresent` to contain only allowed characters, i.e. `ignore_if_present` (underscores are allowed). 
We also fix a few related typos.
=> Fix cases of ignoreIfPresent/ignore_if_present in response header examples

README.md
This PR adds the following information to the explainer: 
* Fenced frame usage enforcement
* Fenced frame config usage
For the URL Selection (`selectURL()`), fenced frame usage will not be required until at least 2026, and we will provide substantial advanced notice before the requirement is put in place. 
Also, the URL Selection operation will return a [fenced frame config](https://github.com/WICG/fenced-frame/blob/master/explainer/fenced_frame_config.md) that can be set as the `config` attribute of a fenced frame element when a flag is passed into the call. If the flag is omitted or not set to `false`, the `selectURL` operation will return an opaque URN that can be set as the `src` attribute of an iframe element.
=> Add fenced frame config and enforcement information

README.md
This PR adds information that event-level reporting for `selectURL()` will be available until at least 2026.
=> Update event-level reporting status for selectURL()

README.md
We clarify that the origin used for shared storage operations invoked via response headers is the origin of the host server sending the response headers. In particular, in the case of redirects, this is the origin of the redirect URL that is accompanied by the `Shared-Storage-Write` response header(s).
=> Clarify which origin is used for redirects

README.md
We specify that the IDL attribute for modifying Shared Storage from response headers is a boolean.
=> Specify IDL attribute `sharedStorageWritable` is boolean

spec.bs
Also, repurpose the algorithm [=check if module added and update status=] to a more general [=check if addModule allowed and update status=], which can contain the user settings check
***
<a href="https://pr-preview.s3.amazonaws.com/WICG/shared-storage/pull/106.html" title="Last updated on Aug 23, 2023, 7:39 PM UTC (e57324a)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/shared-storage/106/b7f5f9c...e57324a.html" title="Last updated on Aug 23, 2023, 7:39 PM UTC (e57324a)">Diff</a>
=> Spec: add the user setting check for addModule()/selectURL()/run()

spec.bs
Update spec for enrollment
***
<a href="https://pr-preview.s3.amazonaws.com/shivanigithub/shared-storage/pull/105.html" title="Last updated on Aug 29, 2023, 10:15 PM UTC (6a945b9)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/shared-storage/105/9d8ae5f...shivanigithub:6a945b9.html" title="Last updated on Aug 29, 2023, 10:15 PM UTC (6a945b9)">Diff</a>
=> Update spec for enrollment

spec.bs
We define Permissions Policy features for Shared Storage and include checks for whether they are enabled, along with a few other minor tweaks.
***
<a href="https://pr-preview.s3.amazonaws.com/WICG/shared-storage/pull/109.html" title="Last updated on Sep 5, 2023, 8:58 PM UTC (cd73167)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/shared-storage/109/0d7bffe...cd73167.html" title="Last updated on Sep 5, 2023, 8:58 PM UTC (cd73167)">Diff</a>
=> Update spec.bs to include Permissions Policy

README.md
We update the explainer to include a brief section on [enrollment and attestation](https://github.com/privacysandbox/attestation/blob/main/README.md).
=> Include attestation & enrollment in explainer

spec.bs
We update the spec to include how operations can be triggered via HTTP response headers, including by way of `fetch()` as well as HTML images and iframes.
***
<a href="https://pr-preview.s3.amazonaws.com/WICG/shared-storage/pull/110.html" title="Last updated on Sep 25, 2023, 6:42 PM UTC (052ea50)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/shared-storage/110/fe6c01d...052ea50.html" title="Last updated on Sep 25, 2023, 6:42 PM UTC (052ea50)">Diff</a>
=> Update spec.bs to include operations via HTTP response header

README.md
The request header added to requests that are eligible to write to shared storage via response header ought to be a "forbidden header" according to the [Fetch specification](https://fetch.spec.whatwg.org/#forbidden-request-header), i.e. a header that JS cannot add or modify.
We were using `Shared-Storage-Writable` as the name of the request header, which was not a forbidden header and could be modified by JS.
This commit updates the explainer to add the prefix `Sec-` in order to make this header forbidden. The new request header attached to eligible outgoing requests will be `Sec-Shared-Storage-Writable: ?1`.
We will update the specification draft accordingly in #121.
=> Update explainer: Add 'Sec-' prefix to request header

spec.bs
The request header added to requests that are eligible to write to shared storage via response header ought to be a "forbidden header" according to the [Fetch specification](https://fetch.spec.whatwg.org/#forbidden-request-header), i.e. a header that JS cannot add or modify.
We were using `Shared-Storage-Writable` as the name of the request header, which was not a forbidden header and could be modified by JS.
This commit is a followup to #120 and updates the specification draft to add the prefix `Sec-` in order to make this header forbidden. The new request header attached to eligible outgoing requests will be `Sec-Shared-Storage-Writable: ?1`.
***
<a href="https://pr-preview.s3.amazonaws.com/WICG/shared-storage/pull/121.html" title="Last updated on Oct 20, 2023, 8:03 PM UTC …
=> Update spec.bs: Add 'Sec-' prefix to request header

README.md
This PR describes how PAA will be timed out after 5 seconds of a Shared Storage operation.
=> Add Private Aggregation timeout information

README.md
- selectURL() and run() will be exposed to the shared storage worklet object. When calling on the default scoped worklet (i.e. sharedStorage.worklet.selectURL()/run()), the behavior is equivalent to sharedStorage.selectURL()/run().
- Users can create new worklets via `const worklet = await sharedStorage.createWorklet(url, options)`. This can be used to start multiple and potentially cross-origin worklets from a single document.
=> Explainer update: Support multiple & cross-origin worklets

README.md
We update the data storage limits so that each origin gets an overall maximum of 5MB of shared storage. The key and values no longer have length restrictions otherwise, and we have removed the limit on number of keys.
=> Update Data Storage Limits in Explainer

README.md
Add the "Shared-Storage-Worklet-Allowed: ?1" response header requirement. This provides an additional layer of security compared to relying solely on CORS.
=> [explainer update] Add "Shared-Storage-Worklet-Allowed: ?1" response header requirement

spec.bs
- selectURL() and run() will be exposed to the shared storage worklet object. When calling on the default scoped worklet (i.e. sharedStorage.worklet.selectURL()/run()), the behavior is equivalent to sharedStorage.selectURL()/run().
- Users can create new worklets via `const worklet = await sharedStorage.createWorklet(url, options)`. This can be used to start multiple and potentially cross-origin worklets from a single document.
- User settings error won't be exposed to the caller (i.e. will be treated as success) in the case of creating or using a cross-origin worklet. This is to prevent leaking user's settings for an arbitrary site.
***
<a href="https://pr-preview.s3.amazonaws.com/WICG/shared-storage/pull/131.html" title="Last updated on Apr 13, 2024, 2:47 AM UTC (9100129)">Preview</a> | …
=> Spec update: Support multiple & cross-origin worklets

spec.bs
This is a follow-up patch for https://github.com/WICG/shared-storage/pull/131. For starting a cross-origin worklet, this response header is needed.
***
<a href="https://pr-preview.s3.amazonaws.com/WICG/shared-storage/pull/152.html" title="Last updated on Apr 25, 2024, 12:33 AM UTC (2a7372f)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/shared-storage/152/52b2115...2a7372f.html" title="Last updated on Apr 25, 2024, 12:33 AM UTC (2a7372f)">Diff</a>
=> Include the "Shared-Storage-Cross-Origin-Worklet-Allowed" response header check

spec.bs
In opaque origin contexts (e.g. sandboxed iframes), we now allow `window.createWorklet(url)` and allow `selectURL()`/`run()` on the resulting worklet object. Those methods were previously disallowed in opaque origin contexts.
Reason: While direct storage access is typically disallowed in sandboxed iframe, that's more of a side effect of having an opaque origin, rather than the original intent of sandboxing. Thus, it should be okay to allow creating new non-opaque contexts via `createWorklet(url)`, and the new contexts can further access shared storage. This enables more flexible functionality within the sandboxed environment while still adhering to the security principles of sandboxing.
***
<a href="https://pr-preview.s3.amazonaws.com/WICG/shared-storage/pull/156.html" title="Last updated …
=> [spec] Allow createWorklet() in opaque origin contexts

spec.bs
We move the enrollment check from a combined enrollment/user preferences check algorithm to the end of the "determine whether shared storage is allowed by context" algorithm, in order to correct a [bug](https://github.com/WICG/shared-storage/issues/159) in the current spec and reflect the current implementation.
***
<a href="https://pr-preview.s3.amazonaws.com/WICG/shared-storage/pull/160.html" title="Last updated on Jun 18, 2024, 8:09 PM UTC (0bd8542)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/shared-storage/160/d57757d...0bd8542.html" title="Last updated on Jun 18, 2024, 8:09 PM UTC (0bd8542)">Diff</a>
=> Spec: Move enrollment check to "is allowed by context" algo

spec.bs
This addresses issue https://github.com/WICG/shared-storage/issues/143. i.e. `FrozenArray<T>` should be prohibited as a parameter type in Web IDL.
***
<a href="https://pr-preview.s3.amazonaws.com/WICG/shared-storage/pull/162.html" title="Last updated on Jun 21, 2024, 4:05 PM UTC (aa5bfd4)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/shared-storage/162/919562d...aa5bfd4.html" title="Last updated on Jun 21, 2024, 4:05 PM UTC (aa5bfd4)">Diff</a>
=> [spec] Use sequence instead of FrozenArray

README.md
Currently, `addModule` only allows same-origin script. This was for convenience of the initial implementation, however, and is no longer necessary. 
The [worklet standard](https://html.spec.whatwg.org/multipage/worklets.html#dom-worklet-addmodule) does not contain this restriction. In fact, we have received [feedback](https://github.com/WICG/shared-storage/issues/127) from developers stating they would like to be able to host and run their worklet script on a separate origin---say a CDN---from the origin that owns and writes their shared storage data.
So we update the explainer to remove the same-origin restriction for `addModule`. We also note that, when the worklet script is cross-origin to the invoking context, the invoking context's origin is used as the partition origin for accessing …
=> Explainer: Allow cross-origin script in addModule & align createWorklet

spec.bs
To address issue #164, we fix the `[=converting=]` auto link by specifying the correct definition to link to. Previously the link was ambiguous, although it only recently starting giving a LINK ERROR.
***
<a href="https://pr-preview.s3.amazonaws.com/WICG/shared-storage/pull/166.html" title="Last updated on Jul 10, 2024, 11:07 PM UTC (7859fe2)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/shared-storage/166/49cf9c8...7859fe2.html" title="Last updated on Jul 10, 2024, 11:07 PM UTC (7859fe2)">Diff</a>
=> Spec bugfix: disambiguate `[=converting=]` link in register algo

spec.bs
We make the spec changes to accompany #158 . 
In particular, we make it possible for `sharedStorage.worklet.addModule()` to create a worklet with cross-origin worklet script. We also align the behavior of `sharedStorage.createWorklet()` with `addmodule()` so that it uses the invoking context's origin as the data partition origin by default, while adding a mechanism to use the script's origin instead if specified.
For a more detailed description, please see #158 .
***
<a href="https://pr-preview.s3.amazonaws.com/WICG/shared-storage/pull/161.html" title="Last updated on Jul 17, 2024, 6:16 PM UTC (420fcc5)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/shared-storage/161/919562d...420fcc5.html" title="Last updated on Jul 17, 2024, 6:16 PM UTC (420fcc5)">Diff</a>
=> Spec: Allow cross-origin script in addModule & align createWorklet

README.md
Some examples have run(data, urls) whereas the formal spec has run(urls, data) as the signature.
https://wicg.github.io/shared-storage/#get-the-select-url-result-index
=> Make run() signature consistent for selectURL

README.md
In worklet code,  use `sharedStorage` directly inside of the class methods instead of `this.sharedStorage`, as the latter is incorrect. 
`this` will refer to the operation object class rather than the worklet. `globalThis` would be needed instead to refer to the worklet, but `sharedStorage` can simply be referred to directly here.
=> Use `sharedStorage` instead of `this.sharedStorage` in worklet

spec.bs
Unforunately this isn't purely editorial, because in the process of adjusting the use of "invoke" a number of other things needed to be clarified.
Namely:
* the operation map now holds JS function objects (i.e., anything with [[Call]])
* these function objects are converted to a specific IDL types only when they are about to be invoked
* the select URL algorithm reacts to the promise rather than expecting its value (or rejection reason) to be immediately available
Part of whatwg/webidl#1425.
***
<a href="https://pr-preview.s3.amazonaws.com/jeremyroman/shared-storage/pull/169.html" title="Last updated on Aug 9, 2024, 8:17 PM UTC (d838e10)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/shared-storage/169/52b4ff5...jeremyroman:d838e10.html" title="Last updated on Aug 9, …
=> Adjust callback function invocation.

README.md, spec.bs
***
<a href="https://pr-preview.s3.amazonaws.com/WICG/shared-storage/pull/172.html" title="Last updated on Aug 20, 2024, 9:26 PM UTC (ea25980)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/shared-storage/172/52b4ff5...ea25980.html" title="Last updated on Aug 20, 2024, 9:26 PM UTC (ea25980)">Diff</a>
=> Merge main to branch

spec.bs
This addresses the IDL misalignment between spec and code: https://github.com/WICG/shared-storage/issues/154.
For the spec, we remove `WindowSharedStorage` and `WorkletSharedStorage` interfaces, and use `[Exposed=Window/SharedStorageWorklet]` to control the exposure of individual fields. We also merge the corresponding methods for set()/append()/delete()/clear().
***
<a href="https://pr-preview.s3.amazonaws.com/WICG/shared-storage/pull/171.html" title="Last updated on Aug 21, 2024, 12:32 AM UTC (53d753b)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/shared-storage/171/ea25980...53d753b.html" title="Last updated on Aug 21, 2024, 12:32 AM UTC (53d753b)">Diff</a>
=> [spec] Remove WindowSharedStorage/WorkletSharedStorage interfaces

README.md
`resolveToConfig` was already described as a supported option for `selectURL()` in the explainer, but we omitted to list in the bullet list of supported options. We correct this previous omission. We also slightly clarify the list to make it apparent which options are supported for `run()` and which for `selectURL()`.
=> [Explainer] Mention `resolveToConfig` in list of supported options

spec.bs
Currently, the Private Aggregation spec integrates with Shared Storage via some monkey patches:
https://patcg-individual-drafts.github.io/private-aggregation-api/#shared-storage-api-monkey-patches
Moves these monkey patches into the main body of the Shared Storage spec, allowing the monkey patches to be removed. This fixes #175 and partially resolves
https://github.com/patcg-individual-drafts/private-aggregation-api/issues/43
***
<a href="https://pr-preview.s3.amazonaws.com/WICG/shared-storage/pull/179.html" title="Last updated on Sep 6, 2024, 4:33 PM UTC (205e451)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/shared-storage/179/1e6f0d7...205e451.html" title="Last updated on Sep 6, 2024, 4:33 PM UTC (205e451)">Diff</a>
=> Move Private Aggregation monkey patch in Shared Storage spec

spec.bs
We combine the monkey patches for HTTP fetch and gather together the new HTTP headers into a single section. Addresses #163 .
***
<a href="https://pr-preview.s3.amazonaws.com/WICG/shared-storage/pull/186.html" title="Last updated on Sep 10, 2024, 7:23 PM UTC (2c1c011)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/shared-storage/186/bb24470...2c1c011.html" title="Last updated on Sep 10, 2024, 7:23 PM UTC (2c1c011)">Diff</a>
=> [spec] Combine monkey patches for HTTP fetch

spec.bs
We address #183  (per-page budgets are missing).
***
<a href="https://pr-preview.s3.amazonaws.com/WICG/shared-storage/pull/187.html" title="Last updated on Sep 10, 2024, 7:24 PM UTC (d3af998)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/shared-storage/187/2c1c011...d3af998.html" title="Last updated on Sep 10, 2024, 7:24 PM UTC (d3af998)">Diff</a>
=> [spec] Add missing per-page budgets to spec

README.md
`selectURL()` currently has two per-page-load budgets that restrict that number of calls made to `selectURL()` on each page-load.  We propose allowing queries to be saved and reused on a per-page basis, where the per-page-load budgets are charged the first time a saved query is run but not for subsequent runs of the saved query during the same page-load. This will be accomplished with a `savedQuery` parameter in the options for `selectURL()` that will name the query.
=> [Explainer] Support Saved Queries in selectURL

README.md
We update the examples to use `try...catch` blocks and also add a short "Error handling" section encouraging their use.
=> [Explainer] Use `try...catch` blocks in examples

README.md
An interestGroups() method is added to the shared storage worklet, to return the Protected Audience interest groups associated with the shared storage origin's owner, with some additional metadata.
This API provides the Protected Audience buyer with a better picture of what’s happening with their users, allowing for Private Aggregation reports (https://github.com/WICG/turtledove/issues/1190).
=> [explainer] Add interestGroups() method to shared storage worklet

spec.bs
We fix issue #190 . (This is a bugfix.)
***
<a href="https://pr-preview.s3.amazonaws.com/WICG/shared-storage/pull/193.html" title="Last updated on Sep 18, 2024, 10:31 PM UTC (1246aea)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/shared-storage/193/82f59f9...1246aea.html" title="Last updated on Sep 18, 2024, 10:31 PM UTC (1246aea)">Diff</a>
=> [spec] Reorder `selectURL` steps for global scope

spec.bs
We fix issue #195 .
***
<a href="https://pr-preview.s3.amazonaws.com/WICG/shared-storage/pull/196.html" title="Last updated on Sep 19, 2024, 12:21 AM UTC (6e4e02a)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/shared-storage/196/f0f79b4...6e4e02a.html" title="Last updated on Sep 19, 2024, 12:21 AM UTC (6e4e02a)">Diff</a>
=> [spec] Specify module map is global scope's relevant settings object's

spec.bs
We update the spec to support saved queries, as a followup to #176.
***
<a href="https://pr-preview.s3.amazonaws.com/WICG/shared-storage/pull/188.html" title="Last updated on Sep 20, 2024, 5:14 PM UTC (fa8183f)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/shared-storage/188/0ebd7a5...fa8183f.html" title="Last updated on Sep 20, 2024, 5:14 PM UTC (fa8183f)">Diff</a>
=> [spec] Support saved queries for selectURL

spec.bs
Switches to using the exported algorithm from the Private Aggregation spec (which will be used in Protected Audience's spec as well)
***
<a href="https://pr-preview.s3.amazonaws.com/WICG/shared-storage/pull/204.html" title="Last updated on Oct 21, 2024, 9:29 PM UTC (76906ef)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/shared-storage/204/e3b4368...76906ef.html" title="Last updated on Oct 21, 2024, 9:29 PM UTC (76906ef)">Diff</a>
=> Spec: use PAA coordinator algorithm

spec.bs
We fix our spec changes so that a query can be queued to reused if it is not the initial query but it is received before the initial query is resolved.
Previously in the spec, only fully resolved queries were being treated as saved. This was an oversight.
***
<a href="https://pr-preview.s3.amazonaws.com/WICG/shared-storage/pull/202.html" title="Last updated on Oct 28, 2024, 10:32 PM UTC (a532f49)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/shared-storage/202/8121c4e...a532f49.html" title="Last updated on Oct 28, 2024, 10:32 PM UTC (a532f49)">Diff</a>
=> [spec] Update saved query to be async

spec.bs
This is the Shared Storage side's spec update to support interestGroups() within shared storage worklet (https://github.com/WICG/shared-storage/pull/180). Sibling spec update PR for Protected Audience: https://github.com/WICG/turtledove/pull/1299.
***
<a href="https://pr-preview.s3.amazonaws.com/WICG/shared-storage/pull/203.html" title="Last updated on Oct 31, 2024, 4:59 PM UTC (5924478)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/shared-storage/203/8121c4e...5924478.html" title="Last updated on Oct 31, 2024, 4:59 PM UTC (5924478)">Diff</a>
=> [spec] Add interestGroups()

spec.bs
Spec update for #198.
This will make it possible for a worklet script to use shared storage data from an arbitrary origin other than the worklet script's origin or the invoking context's origin. The data origin would have to opt-in for data use to occur, as data processing could modify the data origin's data, send reports, and would affect its shared storage privacy budget.
***
<a href="https://pr-preview.s3.amazonaws.com/WICG/shared-storage/pull/206.html" title="Last updated on Nov 13, 2024, 8:54 PM UTC (b272688)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/shared-storage/206/a514c97...b272688.html" title="Last updated on Nov 13, 2024, 8:54 PM UTC (b272688)">Diff</a>
=> [spec] Support custom `dataOrigin` in `createWorklet`

spec.bs
We update mentions of `dataOrigin` in the `createWorklet` algo to be references.
***
<a href="https://pr-preview.s3.amazonaws.com/WICG/shared-storage/pull/208.html" title="Last updated on Nov 23, 2024, 12:40 AM UTC (03fa7ca)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/shared-storage/208/0eccc1d...03fa7ca.html" title="Last updated on Nov 23, 2024, 12:40 AM UTC (03fa7ca)">Diff</a>
=> Fix references to dataOrigin in createWorklet algo

spec.bs
This is part of the Web Locks integration proposal:
https://github.com/WICG/shared-storage/pull/199
https://github.com/WICG/shared-storage/pull/205
How: Let user agent hold a map of origins to lock managers, and for the existing Web Locks API's algorithm, use this manager for shared storage cases.
***
<a href="https://pr-preview.s3.amazonaws.com/WICG/shared-storage/pull/209.html" title="Last updated on Dec 16, 2024, 6:49 AM UTC (f0325f5)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/shared-storage/209/dc07b5a...f0325f5.html" title="Last updated on Dec 16, 2024, 6:49 AM UTC (f0325f5)">Diff</a>
=> [spec] Web Locks integration: support navigator.locks in the worklet

spec.bs
***
<a href="https://pr-preview.s3.amazonaws.com/jyasskin/shared-storage/pull/212.html#web-locks-api-monkey-patches" title="Last updated on Dec 17, 2024, 10:26 PM UTC (9ea55f0)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/shared-storage/212/d07ef02...jyasskin:9ea55f0.html" title="Last updated on Dec 17, 2024, 10:26 PM UTC (9ea55f0)">Diff</a>
=> Avoid exporting duplicate Lock-related definitions from monkeypatches.

.github/workflows/build.yml
PR-Preview is currently [broken](https://github.com/tobie/pr-preview/issues/161) with no fix ETA, so there's no spec builds occurring for new PRs. There should probably be some build checks in place, even if we can't immediately see a preview for the build.
I used the instructions [here](https://docs.github.com/en/actions/writing-workflows/choosing-when-your-workflow-runs/events-that-trigger-workflows#pull_request) to reconfigure this check for `.bs` file changes only.
=> Re-enable builds for PRs in build.yml

spec.bs
The goal is to enable Shared Storage embedders to override the default number of contributions per Private Aggregation report.
To that end, this change adds the `maxContributions` field to the web-visible Private Aggregation config dictionary and plumbs its value into Private Aggregation's "pre-specified report parameters".
Context:
* Explainer: patcg-individual-drafts/private-aggregation-api#146
* Spec change: patcg-individual-drafts/private-aggregation-api#164
***
<a href="https://pr-preview.s3.amazonaws.com/dmcardle/shared-storage/pull/216.html" title="Last updated on Jan 16, 2025, 4:28 PM UTC (e98524b)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/shared-storage/216/6df142d...dmcardle:e98524b.html" title="Last updated on Jan 16, 2025, 4:28 PM UTC (e98524b)">Diff</a>
=> [spec] Enable per-context contribution limits for Private Aggregation

.gitignore, Makefile
The highlights:
* Make can now skip unnecessary work when our targets are already up to date.
* The remote-build recipe now delegates failure detection to curl and preserves its exit status.
* The `clean` target is no longer picky about whether files exist.
* Generated files are now listed in `.gitignore`.
@pythagoraskitty and @xyaoinum, PTAL!
=> Pedantic improvements to Makefile

spec.bs
Currently, `navigator.locks` is the only available attribute on `navigator` (i.e., a SharedStorageWorkletNavigator), and we want to prevent Web Locks functionality during addModule().
This change avoids unintentionally breaking existing code that might legitimately read the navigator object (e.g., expects no Exception thrown) during module loading for purposes unrelated to Web Locks.
***
<a href="https://pr-preview.s3.amazonaws.com/WICG/shared-storage/pull/227.html" title="Last updated on Feb 12, 2025, 11:56 PM UTC (1cb8bcb)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/shared-storage/227/d0d2cb4...1cb8bcb.html" title="Last updated on Feb 12, 2025, 11:56 PM UTC (1cb8bcb)">Diff</a>
=> [spec] During addModule(), switch to allow `navigator` but disallow `navigator.locks`

spec.bs
This prepares for an upcoming change to support transactional batch handling (i.e., these new dedicated database algorithms can be utilized by both the batchUpdate() method and the individual setters methods).
***
<a href="https://pr-preview.s3.amazonaws.com/WICG/shared-storage/pull/230.html" title="Last updated on Mar 13, 2025, 1:53 PM UTC (491dffd)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/shared-storage/230/48acd25...491dffd.html" title="Last updated on Mar 13, 2025, 1:53 PM UTC (491dffd)">Diff</a>
=> [spec] Refactor set() and append() into dedicated database algorithms

spec.bs
The spec changes for https://github.com/WICG/shared-storage/pull/228
Specifically:
- Add a "batch update entries in the database" algorithm that provides transactional support. Switch to call this algorithm for batchUpdate().
- `batchUpdate()` now explicitly throws an exception when any inner method specifies the `withLock` option, preventing unintended behavior.
- For headers, if `with_lock` is specified for any inner method, the whole batch will be ignored as well. This integrates seamlessly with the existing "handle a Shared-Storage-Write response" algorithm, which invokes `batchUpdate()` in the end and will trigger the failure as intended.
***
<a href="https://pr-preview.s3.amazonaws.com/WICG/shared-storage/pull/231.html" title="Last updated on Mar 21, 2025, 8:46 PM UTC …
=> [spec] Support transactional batchUpdate()
